services:
  php:
    build: .
    environment:
    - SERVER_NAME=":8080"
    volumes:
    - .:/app
    - ./container/config/php/zz-custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    - ./container/config/php/zz-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
    ports:
    - 8080:8080
    depends_on:
    - db 
    - cache
    tty: true

  db:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
    - dbdata:/var/lib/mysql
    - ./container/data/mysql:/docker-entrypoint-initdb.d:ro

  cache:
    image: valkey/valkey:9

volumes:
  dbdata: ~
