version: '3'

services:
  nginx:
    image: nginx:1
    volumes:
    - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - .:/var/www/html
    ports:
    - 8080:8080
    depends_on:
    - php-fpm

  # Main application.
  php-fpm:
    build: .
    env_file: .env
    volumes:
    - ./docker/config/php/zz-custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    - .:/var/www/html
    depends_on:
    - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
    - dbdata:/var/lib/mysql
    - ./docker/data/mysql:/docker-entrypoint-initdb.d:ro

volumes:
  dbdata: ~
